-- SHOPMATE AI / SUPABASE SETUP
-- Jalankan seluruh file ini di Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null default 'Makanan Ringan',
  description text,
  price numeric(12,0) not null default 0,
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  store_name text not null default 'ShopMate AI',
  whatsapp_number text not null default '628XXXXXXXXXX'
);

create table if not exists public.admin_users (
  email text primary key
);

alter table public.products enable row level security;
alter table public.settings enable row level security;
alter table public.admin_users enable row level security;

-- PRODUCTS
 drop policy if exists "public can view active products" on public.products;
create policy "public can view active products"
on public.products
for select
using (active = true or auth.role() = 'authenticated');

drop policy if exists "admins manage products" on public.products;
create policy "admins manage products"
on public.products
for all
to authenticated
using (
  exists (
    select 1
    from public.admin_users a
    where lower(a.email) = lower(auth.jwt()->>'email')
  )
)
with check (
  exists (
    select 1
    from public.admin_users a
    where lower(a.email) = lower(auth.jwt()->>'email')
  )
);

-- SETTINGS
 drop policy if exists "public can view settings" on public.settings;
create policy "public can view settings"
on public.settings
for select
using (true);

drop policy if exists "admins manage settings" on public.settings;
create policy "admins manage settings"
on public.settings
for all
to authenticated
using (
  exists (
    select 1
    from public.admin_users a
    where lower(a.email) = lower(auth.jwt()->>'email')
  )
)
with check (
  exists (
    select 1
    from public.admin_users a
    where lower(a.email) = lower(auth.jwt()->>'email')
  )
);

-- ADMIN USERS
-- Admin dapat membaca baris email miliknya sendiri.
drop policy if exists "admins can read admin users" on public.admin_users;
create policy "admins can read admin users"
on public.admin_users
for select
to authenticated
using (lower(email) = lower(auth.jwt()->>'email'));

-- DEFAULT SETTINGS: hanya dibuat jika tabel masih kosong.
insert into public.settings(store_name, whatsapp_number)
select 'ShopMate AI', '628XXXXXXXXXX'
where not exists (
  select 1 from public.settings
);

-- SAMPLE PRODUCTS: hanya dimasukkan jika tabel products masih kosong.
-- Ini memperbaiki error syntax pada versi sebelumnya:
-- INSERT ... VALUES ... WHERE tidak valid di PostgreSQL.
do $$
begin
  if not exists (select 1 from public.products) then
    insert into public.products
      (name, category, description, price, image_url, active)
    values
      ('Keripik Pisang', 'Keripik', 'Renyah & gurih', 18000, 'assets/keripik-pisang.png', true),
      ('Keripik Tempe Daun Jeruk', 'Keripik', 'Gurih & wangi', 26000, 'assets/keripik-tempe.png', true),
      ('Basreng Pedas', 'Makanan Ringan', 'Pedas nagih', 24000, 'assets/basreng-pedas.png', true),
      ('Pilus Keju', 'Makanan Ringan', 'Praktis & lezat', 20000, 'assets/pilus-keju.png', true),
      ('Kacang Bawang', 'Kacang-kacangan', 'Sehat & bergizi', 22000, 'assets/kacang-bawang.png', true);
  end if;
end
$$;

-- Setelah membuat akun admin di Authentication > Users, masukkan emailnya:
-- insert into public.admin_users(email) values ('emailanda@contoh.com');

-- Aktifkan realtime hanya jika products belum terdaftar di publication.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'products'
  ) then
    alter publication supabase_realtime add table public.products;
  end if;
end
$$;
